# Generated by Django 3.2.7 on 2021-10-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_aulas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aulas',
            new_name='Aula',
        ),
    ]
