# Generated by Django 3.2.7 on 2021-10-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_notasaulas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasaulas',
            options={'verbose_name': 'NotaAula', 'verbose_name_plural': 'NotasAulas'},
        ),
    ]
